name:          XWP Engineering Best Practices
title:         XWP Engineering Best Practices
description:   Project engineering best practices used by XWP (h/t 10up).
url:           https://xwp.github.io/engineering-best-practices/
author:
  name:    XWP
  email:   engage@xwp.co
  github:  xwp
  twitter: xwp

markdown:      redcarpet
permalink:     pretty
highlighter:   pygments
encoding:      utf-8
redcarpet:
  extensions: [with_toc_data]
sass:
  sass_dir: _includes/_sass
CONFIG:
  BASE_PATH: https://xwp.github.io/engineering-best-practices

  ASSET_PATH: false
